config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit , :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'

    namespace :profile do
      resources :dashboard, only:[:index]
      resources :ads, only:[:index, :edit, :update, :new, :create]
    end
  end

  root to: 'site/home#index'


  devise_for :admins, :skip => [:registrations] 
  devise_for :members


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
     validates_presence_of(:description) 

  # Scopes
  scope :order_by_description, -> { order(:description) }
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
before_action :find_admin_by_id, only: [:edit, :update, :destroy]
after_action :verify_authorized, only: [:new, :destroy]
after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create 
    @admin = Admin.new(params_admin)
    if @admin.save      
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} cadastrado com sucesso!"
    else
      render :new, notice: 'ocorreu um erro'  
    end        
  end

  def edit 
  end 

  def update 

    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if  @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} editado com sucesso!"
    else
      render :edit, notice: 'ocorreu um erro'  
    end
  end

  def destroy
    authorize @admin
    
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} deletado com sucesso!"
    else      
      redirect_to backoffice_admins_path, notice: "Ocorreu um erro ao deletar o administrador #{@admin.email}"
    end
  end
  

  private 
  def find_admin_by_id
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(policy(@admin).permitted_attributes)
  end  
   
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :find_category_by_id, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new    
  end
  
  
  def create    
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "categoria #{@category.description} cadastrada com sucesso!"
    else
      render :new, notice: 'ocorreu um erro'    
    end
  end

  def update     
    if  @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "categoria #{@category.description} cadastrada com sucesso!"
    else
      render :edit, notice: 'ocorreu um erro'  
    end
  end  

  def edit           
  end

  def destroy    
    if @category.destroy
      redirect_to backoffice_categories_path, notice: "#{@category.description} deletado com sucesso!"
    else      
      redirect_to backoffice_categories_path, notice: "Ocorreu um erro ao deletar #{@category.description}"
    end
  end


  private

  def find_category_by_id
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end
  
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
    attr_accessor :category

    def self.create(params_category)
        @category = Category.new(params_category)

        if @category.valid?
            @category.save!         
        end        
        @category    
    end
end
     
        

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
      
  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

    def edit
      @admin = Admin.find(params[:id])
  
      respond_to do |format|
        format.js
      end
    end
  
    def create
      begin
        AdminMailer.send_message(current_admin,
                                 params[:'recipient-text'],
                                 params[:'subject-text'],
                                 params[:'message-text']).deliver_now
  
        @notify_message = I18n.t('messages.email_delivered')
        @notify_flag = "success"
      rescue
        @notify_message = I18n.t('messages.email_not_delivered')
        @notify_flag = "error"
      end
  
      respond_to do |format|
        format.js
      end
    end
  
  end
  

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'backoffice'

    def pundit_user
        current_admin
    end
    



end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editar Categoria"}  %>

app/views/backoffice/categories/index.html.erb
<h1 class="page-header">CATEGORIAS !</h1>        
<div class="panel panel-default">
  <div class="panel-heading">
      CATEGORIAS
      <%= link_to  new_backoffice_category_path,  class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
        <i class="fa fa-plus"></i>
      <%end%>
      
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th> 
                <th></th>                             
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
            <tr>                      
                <td><%= category.id%></td>
                <td><%= category.description%></td>        
                <td style="width: 82px">
                  <%= link_to  edit_backoffice_category_path(category), class:"btn btn-primary btn-circle"	do %>
                    <i class="fa fa-edit  "></i>
                  <% end %>
                  <%= link_to backoffice_category_path(category), method: :delete, class: "btn btn-danger btn-circle", data: {confirm: "Deseja exluir #{category.description} ?"} 	do %>
                    <i class="fa fa-minus  "></i>
                  <% end %>
                  
                </td>                                     
            </tr>
            <% end %>                          
        </tbody>
      </table>
    </div>  <!-- /.table-responsive -->
  </div> <!-- /.panel-body -->
</div>




      
    

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova Categoria"}  %>