config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit , :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'

    namespace :profile do
      resources :dashboard, only:[:index]
      resources :ads, only:[:index, :edit, :update, :new, :create]
    end
  end

  root to: 'site/home#index'


  devise_for :admins, :skip => [:registrations] 
  devise_for :members


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member

  #validates

  validates :title,:description,:category, :picture, :finish_date, presence: true
  validates :price, numericality: {greater_than: 0}

  # Scopes
  scope :descending_order, -> (quantity = 9){ limit(quantity).order(created_at: :desc) }
  scope :to_the, -> (member){Ad.where(member: member)  }

  #paperclip 
  has_attached_file :picture, styles: { medium: "700x400#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #gem money-rails
  monetize :price_cents
end

app/models/admin.rb
class Admin < ApplicationRecord
 
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
     validates_presence_of(:description) 

  # Scopes
  scope :order_by_description, -> { order(:description) }
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit 
   # Manages Pundit Errors
   rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception
  layout :layout_by_resource

  private
  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "devise_backoffice"
    else
      "application"
    end
  end
  
  def user_not_authorized
    flash[:alert] = I18n.t('messages.not_authorized')
    redirect_to(request.referrer || root_path)
  end
  
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
before_action :find_admin_by_id, only: [:edit, :update, :destroy]
after_action :verify_authorized, only: [:new, :destroy]
after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create 
    @admin = Admin.new(params_admin)
    if @admin.save      
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} cadastrado com sucesso!"
    else
      render :new, notice: 'ocorreu um erro'  
    end        
  end

  def edit 
  end 

  def update 

    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if  @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} editado com sucesso!"
    else
      render :edit, notice: 'ocorreu um erro'  
    end
  end

  def destroy
    authorize @admin
    
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} deletado com sucesso!"
    else      
      redirect_to backoffice_admins_path, notice: "Ocorreu um erro ao deletar o administrador #{@admin.email}"
    end
  end
  

  private 
  def find_admin_by_id
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(policy(@admin).permitted_attributes)
  end  
   
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :find_category_by_id, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new    
  end
  
  
  def create    
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "categoria #{@category.description} cadastrada com sucesso!"
    else
      render :new, notice: 'ocorreu um erro'    
    end
  end

  def update     
    if  @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "categoria #{@category.description} cadastrada com sucesso!"
    else
      render :edit, notice: 'ocorreu um erro'  
    end
  end  

  def edit           
  end

  def destroy    
    if @category.destroy
      redirect_to backoffice_categories_path, notice: "#{@category.description} deletado com sucesso!"
    else      
      redirect_to backoffice_categories_path, notice: "Ocorreu um erro ao deletar #{@category.description}"
    end
  end


  private

  def find_category_by_id
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end
  
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
      
  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

    def edit
      @admin = Admin.find(params[:id])
  
      respond_to do |format|
        format.js
      end
    end
  
    def create
      begin
        AdminMailer.send_message(current_admin,
                                 params[:'recipient-text'],
                                 params[:'subject-text'],
                                 params[:'message-text']).deliver_now
  
        @notify_message = I18n.t('messages.email_delivered')
        @notify_flag = "success"
      rescue
        @notify_message = I18n.t('messages.email_not_delivered')
        @notify_flag = "error"
      end
  
      respond_to do |format|
        format.js
      end
    end
  
  end
  

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'backoffice'

    def pundit_user
        current_admin
    end
    



end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(15)
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
    layout "profile"
    
end
  

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>				
  <%if @admin.errors.any?%>         
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>   
      <% @admin.errors.full_messages.each do |message|%>
        <ul>
          <li>                  
            <%= message %>
          </li>
        </ul>
      <%end%>
    </div>
  <%end%>
        
<div class="panel panel-default">
  <div class="panel-heading">
      <%= action %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for([:backoffice, @admin] , role:"form") do |f| %> 
        <div class="form-group">
          <label>Nome Admnistrador</label>
          <%= f.text_field :name, class: "form-control", placeholder:"Digite o nome do administrador" %>
        </div>																			
        <div class="form-group">
          <label>Email Admnistrador</label>
          <%= f.text_field :email, class: "form-control", placeholder:"Digite o email do administrador" %>
        </div>		
        
        <% if policy(@admin).edit? %>
          <div class="form-group">
            <%= f.label :role %>
              <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                <div class="radio">
                  <%= b.label { b.radio_button + b.text} %>
                </div>
                <% end %>
          </div>
        <%end%>
        
        <div class="form-group">
          <label>Senha Admnistrador</label>
          <%= f.password_field :password, class: "form-control", placeholder:"Digite a senha" %>
        </div>																			
        <div class="form-group">
          <label>Confirmar senha</label>
          <%= f.password_field  :password_confirmation, class: "form-control", placeholder:"Digite a confirmação da senha" %>
        </div>																			
        <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
    </div>            
  </div>
    <!-- /.panel-body -->
</div>
			

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html"><%= t('app.backoffice_subtitle') %></a>
    </div>
    <!-- /.navbar-header -->
    
    <ul class="nav navbar-top-links navbar-right">
    
    <li><%= current_admin.email %></li>
    
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <%= link_to destroy_admin_session_path, method: :delete do %>
                    <i class="fa fa-sign-out fa-fw"></i>
                    Sair
                <% end %>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    
    <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
          <li>   
            <%= link_to  backoffice_path	do %>             
                <i class="fa fa-dashboard fa-fw"></i>Dashboard
            <%end%>               
          </li>          
          <li> 
              <%= link_to  backoffice_categories_path	 do %>               
                <i class="fa fa-th-list fa-fw"></i>Categories
              <% end %>
          </li>          
          <li> 
              <%= link_to  backoffice_admins_path	 do %>               
                <i class="fa fa-users fa-fw"></i>Administradores
              <% end %>
          </li>          
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>